#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libevent
Version  : 2.0.22
Release  : 14
URL      : http://downloads.sourceforge.net/levent/libevent-2.0.22-stable.tar.gz
Source0  : http://downloads.sourceforge.net/levent/libevent-2.0.22-stable.tar.gz
Summary  : libevent_pthreads adds pthreads-based threading support to libevent
Group    : Development/Tools
License  : BSD-3-Clause
Requires: libevent-bin
Requires: libevent-lib
BuildRequires : openssl-dev
BuildRequires : pkgconfig(zlib)
BuildRequires : sed

%description
0. BUILDING AND INSTALLATION (Briefly)
$ ./configure
$ make
$ make verify   # (optional)
$ sudo make install

%package bin
Summary: bin components for the libevent package.
Group: Binaries

%description bin
bin components for the libevent package.


%package dev
Summary: dev components for the libevent package.
Group: Development
Requires: libevent-lib
Requires: libevent-bin

%description dev
dev components for the libevent package.


%package lib
Summary: lib components for the libevent package.
Group: Libraries

%description lib
lib components for the libevent package.


%prep
%setup -q -n libevent-2.0.22-stable

%build
%configure --disable-static --disable-libevent-regress
make V=1 %{?_smp_mflags}

%check
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/event_rpcgen.py

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/include/event2/buffer.h
/usr/include/event2/buffer_compat.h
/usr/include/event2/bufferevent.h
/usr/include/event2/bufferevent_compat.h
/usr/include/event2/bufferevent_ssl.h
/usr/include/event2/bufferevent_struct.h
/usr/include/event2/dns.h
/usr/include/event2/dns_compat.h
/usr/include/event2/dns_struct.h
/usr/include/event2/event-config.h
/usr/include/event2/event.h
/usr/include/event2/event_compat.h
/usr/include/event2/event_struct.h
/usr/include/event2/http.h
/usr/include/event2/http_compat.h
/usr/include/event2/http_struct.h
/usr/include/event2/keyvalq_struct.h
/usr/include/event2/listener.h
/usr/include/event2/rpc.h
/usr/include/event2/rpc_compat.h
/usr/include/event2/rpc_struct.h
/usr/include/event2/tag.h
/usr/include/event2/tag_compat.h
/usr/include/event2/thread.h
/usr/include/event2/util.h
/usr/lib64/*.so
/usr/lib64/pkgconfig/*.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/*.so.*
